
const schema_constans = {
  AUTOGENERATED: 'autogenerated',
  EMAIL: 'email',

  VALIDATION: {
    NOT_EMPTY: 'not_empty',
    EMAIL: 'email',
    UNIQUE: 'unique',
  }

}


module.exports = schema_constans
